### ISSUE TITLE
No module named 'graphviz'

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/croo#12]
Hello, I using Croo v0.3.1 installed in the conda environment with encode-atac-seq-pipeline v1.5.4. It looks like `graphviz` needs to be added as a dependency:
```
Traceback (most recent call last):
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/bin/croo", line 11, in <module>
    from croo.croo import main
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/croo/croo.py", line 17, in <module>
    from .croo_html_report import CrooHtmlReport
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/croo/croo_html_report.py", line 11, in <module>
    from .croo_html_report_task_graph import CrooHtmlReportTaskGraph
  File "/labs/smontgom/nicolerg/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/croo/croo_html_report_task_graph.py", line 11, in <module>
    from graphviz import (Source, render)
ModuleNotFoundError: No module named 'graphviz'
```
`pip install graphviz` within the conda environment fixed it.

**Comment by leepc12** [comment]
This is already fixed in 0.3.2.

**Comment by annashcherbina** [comment]
As of 0.3.3 you also have to run `apt-get install graphviz` (or equivalent for your operating system), as pygraphviz does not place the dot program on the PATH by default. If using anaconda, you can also run `conda install pydot-ng` in addition to `conda install pygraphviz`. 

@leepc12 you might consider adding `pydot-ng` as a dependency or clarifying in the docs that pygraphviz by itself will not give you the needed dot utility and the user must also install dot. 

@nicolerg if you're usinig sherlock, you can run `module load viz graphviz`

**Comment by leepc12** [comment]
`conda install pydot-ng -c anaconda` conflicts with packages in `requirements.txt` for two ENCODE pipelines (atac/chip). Also `anaconda` is not an official Conda repo since 4.7.

Try `apt install graphviz` if you can `sudo` or add `--no-graph` to the command line.
