### ISSUE TITLE
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'

### ISSUE THREAD

**Issue by wangxiangxiu** [ENCODE-DCC/croo#42]
when run croo,
Traceback (most recent call last):
  File "/home/data/t0302015/.local/bin/croo", line 3, in <module>
    from croo.cli import main
  File "/home/data/t0302015/.local/lib/python3.8/site-packages/croo/__init__.py", line 1, in <module>
    from .croo import Croo
  File "/home/data/t0302015/.local/lib/python3.8/site-packages/croo/croo.py", line 8, in <module>
    from .cromwell_metadata import CromwellMetadata
  File "/home/data/t0302015/.local/lib/python3.8/site-packages/croo/cromwell_metadata.py", line 8, in <module>
    from .croo_wdl_parser import CrooWDLParser
  File "/home/data/t0302015/.local/lib/python3.8/site-packages/croo/croo_wdl_parser.py", line 3, in <module>
    from caper.wdl_parser import WDLParser
  File "/home/data/t0302015/.local/lib/python3.8/site-packages/caper/__init__.py", line 1, in <module>
    from .caper_client import CaperClient, CaperClientSubmit
  File "/home/data/t0302015/.local/lib/python3.8/site-packages/caper/caper_client.py", line 9, in <module>
    from .cromwell import Cromwell
  File "/home/data/t0302015/.local/lib/python3.8/site-packages/caper/cromwell.py", line 10, in <module>
    from .cromwell_metadata import CromwellMetadata
  File "/home/data/t0302015/.local/lib/python3.8/site-packages/caper/cromwell_metadata.py", line 10, in <module>
    import pandas as pd
  File "/home/data/t0302015/.local/lib/python3.8/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/home/data/t0302015/.local/lib/python3.8/site-packages/pandas/compat/__init__.py", line 14, in <module>
    from pandas._typing import F
  File "/home/data/t0302015/.local/lib/python3.8/site-packages/pandas/_typing.py", line 120, in <module>
    np.random.BitGenerator,
AttributeError: module 'numpy.random' has no attribute 'BitGenerator'

How can I fix it? thanks

**Comment by wangxiangxiu** [comment]
The problem was fixed by updating numpy.
